export * from './Hero';
export * from './Navbar';
export * from './Process';
export * from './Philosophy';
export * from './MarketingApp';
export * from './Footer';
export * from './Services';
export * from './Contact';
export * from './About';
